---
#System 
php_modules: [ 'php-curl', 'php-gd', 'php-mbstring', 'php-xml', 'php-xmlrpc', 'php-soap', 'php-intl', 'php-zip' ]

#MySQL 
mysql_root_password: "senai"
mysql_db: "wordpress"
mysql_user: "senai"
mysql_password: "senai"

#HTTP 
http_host: "wp-senai.local"
http_conf: "wp-senai.conf"
http_port: "80"